name: Build AAS Auth Service

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: |
          git clone https://gitlab.eclipse.org/eclipse/xfsc/authenticationauthorization.git . &&\
          wget https://raw.githubusercontent.com/merlot-education/merlot-aas/109741fd6b6f3caf11694ae0c72de2fb4b8a18c1/cors-config.patch &&\
          git apply cors-config.patch

      - name: Image tag
        if: startsWith(github.ref, 'refs/heads/')
        shell: bash {0}
        run: |
          tag="$GITHUB_SHA"
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Repo + image name environment variable
        run: echo "repository=${GITHUB_REPOSITORY,,}/aas/auth-service" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.repository }}:${{ env.tag }},ghcr.io/${{ env.repository }}:latest
          build-args: |
            ENVIRONMENT=${{ env.environment }}
