name: Build AAS Auth Service

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Repo environment variable
        run: echo "repository=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Get pom.xml from upstream
        run: wget https://gitlab.eclipse.org/eclipse/xfsc/authenticationauthorization/-/raw/main/service/pom.xml?ref_type=heads

      - name: Get Project Version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: https://gitlab.eclipse.org/mjuergenscg/authenticationauthorization.git#feature/higher-res-qr
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.repository }}/aas/auth-service:${{ steps.getVersion.outputs.version }},ghcr.io/${{ env.repository }}/aas/auth-service:latest
