name: Build PCM App

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone
      run: git clone https://gitlab.eclipse.org/eclipse/xfsc/pcm/app.git .
      
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: npm
      run: |
        npm i -g yarn && yarn install
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
      working-directory: ./android

    - uses: actions/upload-artifact@v3
      with:
        name: pcm-app.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
